version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  airflow-webserver:
    build: .
    restart: always
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
    env_file:
      - .env
    volumes:
      - ./:/opt/airflow
    ports:
      - "8080:8080"
      - "5000:5000"  # Flask nếu có app.py
    command: |
      bash -c "
        airflow db init &&
        airflow users create --username admin --firstname admin --lastname user --role Admin --email admin@example.com --password admin || true &&
        exec airflow webserver
      "


  airflow-scheduler:
    build: .
    restart: always
    depends_on:
      - postgres
      - airflow-webserver
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    env_file:
      - .env
    volumes:
      - ./:/opt/airflow
    command: bash -c "exec airflow scheduler"

volumes:
  postgres_data:
